### ISSUE TITLE
Error when building site with latest gems

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/jekyll-external-links#1]
```rb
$ bundle exec jekyll serve --trace
Configuration file: /Users/me/src/isotc211/www.isotc211.org/_config.yml
 Theme Config file: /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-theme-isotc211-0.5.8/_config.yml
            Source: /Users/me/src/isotc211/www.isotc211.org
       Destination: /Users/me/src/isotc211/www.isotc211.org/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
  Liquid Exception: undefined method `asset_file?' for #<Jekyll::AsciiDoc::Excerpt:0x00007f9b4bb20910> in /_layouts/posts.html
bundler: failed to load command: jekyll (/Users/me/.rbenv/versions/2.6.5/bin/jekyll)
NoMethodError: undefined method `asset_file?' for #<Jekyll::AsciiDoc::Excerpt:0x00007f9b4bb20910>
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-external-links-0.1.2/lib/jekyll-external-links/external_links.rb:46:in `mark_links_in_page_or_document'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-external-links-0.1.2/lib/jekyll-external-links/external_links.rb:68:in `block in <top (required)>'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.6/lib/jekyll/hooks.rb:103:in `block in trigger'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.6/lib/jekyll/hooks.rb:102:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.6/lib/jekyll/hooks.rb:102:in `trigger'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-asciidoc-3.0.0/lib/jekyll-asciidoc/excerpt.rb:45:in `trigger_hooks'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-asciidoc-3.0.0/lib/jekyll-asciidoc/excerpt.rb:31:in `output'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.6/lib/jekyll/excerpt.rb:70:in `to_s'
```

**Comment by ronaldtse** [comment]
@strogonoff could you please help fix this? Thanks!

**Comment by strogonoff** [comment]
@ronaldtse 

When our plugin registers the `post_render` hook for `:documents`, it expects documents to be passed. However, `jekyll-asciidoc` calls `post_render` hook for its _excerpts_. 

I think it’s a recent thing in jekyll-asciidoc. Although even if this was the case before, it was masked in Jekyll 2.x where Excerpt used to be a Convertible (it’s not a Convertible as of Jekyll 3.x).

Since [running hooks for excerpts is not how things are done in Jekyll](https://github.com/jekyll/jekyll/issues/7018#issuecomment-389822331), the fix will be a workaround specifically to deal with jekyll-asciidoc.

**Comment by strogonoff** [comment]
@ronaldtse Compatibility with jekyll-asciidoc behavior should be improved in 0.1.3. I’ll leave this open for now, even though it’s tested briefly with the bundled example site, that doesn’t cover all cases such as collections and excerpts.

**Comment by ronaldtse** [comment]
It's fixed! Thanks @strogonoff !
